// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Akka.FSharp.Extensions")>]
[<assembly: AssemblyProductAttribute("Akka.FSharp.Extensions")>]
[<assembly: AssemblyDescriptionAttribute("Set of extensions to the official Akka.NET F# API.")>]
[<assembly: AssemblyVersionAttribute("0.3.5")>]
[<assembly: AssemblyFileVersionAttribute("0.3.5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Akka.FSharp.Extensions"
    let [<Literal>] AssemblyProduct = "Akka.FSharp.Extensions"
    let [<Literal>] AssemblyDescription = "Set of extensions to the official Akka.NET F# API."
    let [<Literal>] AssemblyVersion = "0.3.5"
    let [<Literal>] AssemblyFileVersion = "0.3.5"
